twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        SecurityService: '@App\Service\FrontSecurityService'
        RandomService: '@App\Service\RandomService'
    form_themes: ['bootstrap_4_layout.html.twig']
